import type { TranscriptResult, TranscriptVariant, SeoContent } from '@/types'

export function generateMarkdown(
  transcript: TranscriptResult,
  variants?: Record<string, TranscriptVariant>,
  seo?: SeoContent
): string {
  const lines: string[] = []

  lines.push(`# ${transcript.title}`)
  lines.push('')
  lines.push(`**Channel:** ${transcript.channelName || 'Unknown'}`)
  lines.push(`**Video:** https://www.youtube.com/watch?v=${transcript.videoId}`)
  lines.push(`**Language:** ${transcript.language}`)
  lines.push('')

  if (seo?.seoSummary) {
    lines.push('## Summary')
    lines.push('')
    lines.push(seo.seoSummary)
    lines.push('')
  }

  if (seo?.seoTopics && seo.seoTopics.length > 0) {
    lines.push('## Key Topics')
    lines.push('')
    for (const topic of seo.seoTopics) {
      lines.push(`- ${topic}`)
    }
    lines.push('')
  }

  lines.push('## Transcript')
  lines.push('')

  for (const segment of transcript.transcript) {
    lines.push(`**[${segment.tsDisplay}]** ${segment.text}`)
    lines.push('')
  }

  // FAQ - from seo or from variants
  let faqList: { q: string; a: string }[] = seo?.seoFaq || []
  if (faqList.length === 0 && variants?.faq) {
    try { faqList = JSON.parse(variants.faq.content) } catch { /* ignore */ }
  }
  if (faqList.length > 0) {
    lines.push('## FAQ')
    lines.push('')
    for (const faq of faqList) {
      lines.push(`**Q: ${faq.q}**`)
      lines.push('')
      lines.push(faq.a)
      lines.push('')
    }
  }

  lines.push('---')
  lines.push('')
  lines.push('*Generated by [Transcript Workflow Toolkit](https://transcript-toolkit.com)*')

  return lines.join('\n')
}

export function generatePlainText(
  transcript: TranscriptResult,
  variants?: Record<string, TranscriptVariant>
): string {
  const lines: string[] = []

  lines.push(transcript.title)
  lines.push(`Channel: ${transcript.channelName || 'Unknown'}`)
  lines.push(`Source: https://www.youtube.com/watch?v=${transcript.videoId}`)
  lines.push('')

  if (variants?.cleaned) {
    lines.push(variants.cleaned.content)
  } else {
    for (const segment of transcript.transcript) {
      lines.push(`[${segment.tsDisplay}] ${segment.text}`)
    }
  }

  return lines.join('\n')
}

export function generateClipboardText(transcript: TranscriptResult): string {
  const MAX_LENGTH = 10000
  let text = ''

  for (const segment of transcript.transcript) {
    const line = `[${segment.tsDisplay}] ${segment.text}\n`
    if (text.length + line.length > MAX_LENGTH) {
      text += '\n... (truncated)'
      break
    }
    text += line
  }

  return text
}
